export const STYLES = [
  'Dessin animé',
  'Photo années 50',
  'Peinture réaliste',
  'Dessin au crayon',
  'Figurine en argile',
  'Cyberpunk',
  'Steampunk',
  'Aquarelle',
  'Pop Art',
  'Impressionnisme',
  'Surréalisme',
  'Art linéaire minimaliste',
  'Rendu 3D',
  'Pixel Art',
  'BD vintage',
  'Vitrail',
  'Art Déco',
  'Cubisme',
  'Art Nouveau',
  'Fantasy',
  'Vaporwave',
  'Style Gothique',
  'Manga',
  'Mosaïque',
] as const;
